name: product-explorer

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - 'main'
      - 'feature/**'
      - 'bug/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Build
      run: mvn -B package --file pom.xml -DskipTests

    - name: Run Tests
      run: mvn test
